//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Интернет
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Application
    {
        public int ApplicationID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Desc { get; set; }
        public Nullable<int> TariffID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
